deployment-chart:
  image:
    repository: custom-nginx
    tag: stable
  service:
    port: 8080
  serviceAccount:
    create: false
  autoscaling:
    enabled: false

ingress-chart:
  hosts:
    - name: custom1.com
    - name: custom2.com